#!/bin/bash
count=$(ls `dirname $0`/target | grep '\.jar$' | wc -l)

if [ "$count" -eq 1 ]
then
	java -jar `dirname $0`/target/*.jar --spring.profiles.active=$1 --spring.cloud.config.uri=http://localhost:8888/
else
	echo "Error: There are too many jar files in the target folder."
fi
